server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh #payment_rout #路由的id,没有固定规则但要求唯一，建议配合服务名称使用
          uri: lb://CLOUD-PAYMENT-SERVICE
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_rout #路由的id,没有固定规则但要求唯一，建议配合服务名称使用
          uri: lb://CLOUD-PAYMENT-SERVICE
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentPage/** #断言，路径相匹配的进行路由
#Eureka 配置
eureka:
  client:
    #表示是否将自己注册进入eurekaServer 默认是true
    register-with-eureka: true
    #是否从EurekaServer抓取已有注册信息，默认为true,单节点无所谓，几圈必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
